language: node_js
node_js:
  - "lts/*"

addons:
  sonarcloud:
    organization: "ferzerkerx-github"
    token:
      secure: "SglavZvViyMuuR+i+AYNm4a6fDPqmf6oAv3As7pMXhunjoZCDdAboUi8rwXfmbwv5dt3AodFvA0a6pW+rkPhaQlxfl1reL/ZOnXmNYyQQOWmVDFaxPZuZvdSlyg7nhozJURvkh/GXeR7cNmSNDWN3cP1rnMhC7TIrGkGCzTRj1cNfHs9DWaUnkBv2F0FQOB4MwzJIZM4i8hdAqq48TfVNW5wuY21Rzu2SYqPd294/rFfh9yw8MN/owwDCxdntJVVPlwgS4JiABf1sGHByA0iGQefda0oAbye1qc3kDobga7MeO1eAhfJLCVlTeeKIsQJks6eyPdQkXzbH3lF908ix1cPpuUVV2eqIpwNZHFCnwwhsVv48nCFvSeUo1WnaxQ+jQYfPbAO9Hms5OHUwQLQCgYB2KhjvGtzlJowe/YD+NUsQnAPoSbvhRUvdJgZ/00mnGn/i3pyZ7cVJm5nX+iT3CksVGd9JT5HJldKLferjvtzcb88AIWJ9VgcGxFrIPLTOS4kSIItqc9D+9xiu5MY8lJKK5/JcbqBn1trG072I2rTOFctfTOj1KkonpvA6dhZyOGSB4yNoqUZ/+rNRBJ297/iY2akCuJ9v+q5ZXkrXI/fD1Hnr23DHHk/ADH+rKpGsAJ3pQ+mZoEogrJeprdr5n2E2yUTPb56A/ASKH2LbIU="
env:
  secure: "o3iKU9VxcTqj09Tne8uiTB5F9XzgM6OEnRI1NtfSWXOMzKMz8OxQIrS0INBHRzH1dq3KafC18aI4oa5gCwqT8i9IFqK7UU/fH+A251xl8t+DzRVc/BE3Lrfc59YgqtbQ/lu//+cL9hvnuC4bKjtEZdTwxRdBif+UT+0k16+VVjqM1xYUFSvAqn7oF7vDfx4tJCoITKjrHD9xG+ZdAK4eOtePYnWs8kCvEpPH5WAMIgrxa6AsBdGpHBUwy3gQ+HdIyCixb8miIT2mzZK88WzS+KkfojuBmghOFVabOP1n76VqDRVj5Q9Nq9yu3xTaCc8077ZRMWIw8Pra+MMS3qBctumrBavqHMFeNj5ETr7BVbfXDVO+PIoZg516pvRTNcdOy1ljcpsJ5rcQhjJNEFIra7BHrmlvfmNxQOi45UgXuP1pN3o64rbJJq/trMPl2kGgOLnYYx1TM+1ioXR1SNa7ZwvMPZaLJ9zW3XtZ2HBUI+WtBohtd3hKridleBdaNuOt1qZS6Pn1OVKI6oRJZ/fWNkkauQbBetPH4DOQ84sKkzlr9tfI2sT6xYM3CbHXwD6Eu6BFjr1dXsbmMXxxetX/gCy0BOYJ7WUOY5uqIpvlMi+6xyServ2iFUPVUb8j8UQvHJeX/0GLX0OjPxF+PDtMxBoEQIpxLyknrkC1NP0PDYk="
cache:
  directories:
    - "node_modules"

install:
  - "npm install"
  - "npm install -g snyk"

script:
  - "sonar-scanner"
  - "snyk test"

after_success:
  - snyk monitor